version: '2'
services:

  #  The Application
  app:
    image: shakyshane/laravel-app
    working_dir: /var/www
    volumes:
      - /var/www/storage
      - /var/www/public/uploads
      - /var/www/bootstrap/cache
      - .env:/var/www/.env
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=cache"

  # The Web Server
  web:
    image: shakyshane/laravel-web
    volumes:
      - "${LE_DIR}:/etc/letsencrypt"
    ports:
      - 80:80
      - 443:443

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  cache:
    image: redis:3.0-alpine

volumes:
  dbdata:
